### ISSUE TITLE
Support for more Transformation Logic

### ISSUE THREAD

**Issue by Gouravmoy** [Gouravmoy/QueryGenerator#15]
Handling all kinds of operators , aggregate / analytical functions like Rank, Partition.

Please refer this for more information,
- [Oracle Analytical Functions Link](http://docs.oracle.com/cd/E11882_01/server.112/e41084/functions004.htm#SQLRF06174)

Aggregate functions

Aggregate Functions
- MIN -> returns the smallest value in a given column
- MAX ->    returns the largest value in a given column
- SUM ->    returns the sum of the numeric values in a given column
- AVG ->    returns the average value of a given column
- COUNT ->  returns the total number of values in a given column
- COUNT(*) ->   returns the number of rows in a table

Priority - **Medium**

**Comment by VivekBasidoni** [comment]
Working as expected.
