### ISSUE TITLE
Support for Handling huge volume of records

### ISSUE THREAD

**Issue by Gouravmoy** [Gouravmoy/QueryGenerator#18]
Support for Handling huge volume of records in the Execute Query UI

Priority - **Low**

**Comment by Gouravmoy** [comment]
No concrete methord found. Here are some of the algorithims those can be implemented
[hugeVolume Algo.txt](https://github.com/Gouravmoy/QueryGenerator/files/221165/hugeVolume.Algo.txt)

Also Some other methods
- Storing the result-set in a file
- Pagination 
- [Scrolable Cursor](https://jdbc.postgresql.org/documentation/head/query.html#fetchsize-example)
- [StackOverFlow Link](http://stackoverflow.com/questions/3682614/jdbc-how-to-read-all-rows-from-huge-table)
- [Code Ranch Link](http://www.coderanch.com/t/304547/JDBC/databases/Resultset-million-rows)

**Comment by Gouravmoy** [comment]
[https://jdbc.postgresql.org/documentation/head/query.html#fetchsize-example](Scrolable Cursor)

**Comment by Gouravmoy** [comment]
[Possible Solution](http://stackoverflow.com/questions/1318354/what-does-statement-setfetchsizensize-method-really-do-in-sql-server-jdbc-driv/15559710#15559710) by using 
// Turn use of the cursor on.
Statement .setFetchSize(50);

**Comment by Gouravmoy** [comment]
Completed. Ready to test

**Comment by VivekBasidoni** [comment]
[Try Thisalso](http://stackoverflow.com/questions/1080852/fastest-way-to-iterate-through-large-table-using-jdbc)

**Comment by Gouravmoy** [comment]
Implemented
