### ISSUE TITLE
QueryColorUtil adding some extra characters

### ISSUE THREAD

**Issue by VivekBasidoni** [Gouravmoy/QueryGenerator#5]
Expected:
Case 
 When COMPANY.IDCOMPANY = 'accaca' Then COMPANY.IDCOMPANY 
End Case

Actual:
[Defect.xlsx](https://github.com/Gouravmoy/QueryGenerator/files/206377/Defect.xlsx)
Case When COMPANY.IDCOMPANY = 'accaca' Then Then COMPANY.IDCOMPANY End Case

**Comment by Gouravmoy** [comment]
Fixed.Working as expected.
![image](https://cloud.githubusercontent.com/assets/14962826/14318313/d7e44e06-fc29-11e5-9b70-15dcc84a0e18.png)
