### ISSUE TITLE
Select UI Error in Query Generation

### ISSUE THREAD

**Issue by Gouravmoy** [Gouravmoy/QueryGenerator#6]
In Select UI, When moving to InnerJoin UI, the Query is not coming with the select row.

In Select UI page befor hitting the Next Button
![image](https://cloud.githubusercontent.com/assets/14962826/14318883/8d8c5012-fc2c-11e5-8490-d983bc35e193.png)

After Hitting the Next Button
![image](https://cloud.githubusercontent.com/assets/14962826/14318919/a820ec80-fc2c-11e5-9932-af9f59eaf0c4.png)

**Comment by VivekBasidoni** [comment]
Working as expected hence closing defect
Before next button is clicked
![image](https://cloud.githubusercontent.com/assets/17848343/14339273/fda1c0e4-fc9a-11e5-962e-dc1736bf862e.png)
After next button is clicked
![image](https://cloud.githubusercontent.com/assets/17848343/14339279/0984404e-fc9b-11e5-80f9-79961904072b.png)
